/*-------- DML da tabela T_CPT_CLIENTE -------*/

UPDATE T_CPT_CLIENTE 
SET ID_CLIENTE = 55555 
WHERE ID_CLIENTE = 11111;
 
DELETE FROM T_CPT_CLIENTE 
WHERE ID_ITEM = 34343; 


/*--------- DML da tabela T_CPT_CARDAPIO ----------*/

UPDATE T_CPT_CARDAPIO 
SET ID_CARDAPIO = 00001 
WHERE ID_CLIENTE = 22222; 

DELETE FROM T_CPT_CARDAPIO 
WHERE ID_CARDAPIO = 55566; 


/*--------- DML da tabela T_CPT_PEDIDO ----------*/

UPDATE T_CPT_PEDIDO 
SET DT_PEDIDO = 16/06/2000 
WHERE DT_PEDIDO = 16/05/2002; 

DELETE FROM T_CPT_PEDIDO 
WHERE ID_PEDIDO = 12365; 


/*--------- DML da tabela T_CPT_ITEM ----------*/

UPDATE T_CPT_ITEM 
SET DS_ITEM = “Alcoól” 
WHERE ID_ITEM = 14230; 

DELETE FROM T_CPT_PEDIDO 
WHERE ID_ITEM = 23728; 