/*----------- DDL da tabela T_CPT_CLIENTE ------------*/

CREATE TABLE T_CPT_CLIENTE(
ID_CLIENTE NUMBER(5) NOT NULL
);

 ALTER TABLE T_CPT_CLIENTE 
ADD CONSTRAINT PK_CPT_CLIENTE 
 PRIMARY KEY (ID_CLIENTE); 
 
 ALTER TABLE T_CPT_CLIENTE 
ADD CONSTRAINT FK_CPT_CLIENTE_PEDIDO
 FOREIGN KEY (ID_PEDIDO)
 REFERENCES T_CPT_PEDIDO (ID_PEDIDO);


/*------------ DDL da tabela T_CPT_CARDAPIO ---------------*/

CREATE TABLE T_CPT_CARDAPIO(
ID_CARDAPIO NUMBER(5) NOT NULL
);

 ALTER TABLE T_CPT_CARDAPIO 
ADD CONSTRAINT PK_CPT_CARDAPIO
 PRIMARY KEY (ID_CARDAPIO);


/*------------ DDL da tabela T_CPT_PEDIDO ----------------*/

CREATE TABLE T_CPT_PEDIDO(
ID_PEDIDO NUMBER(5) NOT NULL,
DT_PEDIDO DATE NOT NULL,
VL_TOTAL NUMBER(10,2) NOT NULL,
QT_ITEM NUMBER(5) NOT NULL
);

 ALTER TABLE T_CPT_PEDIDO
ADD CONSTRAINT PK_CPT_PEDIDO
 PRIMARY KEY (ID_PEDIDO);


/*-------------  DDL da tabela T_CPT_ITEM --------------*/

CREATE TABLE T_CPT_ITEM(
ID_ITEM NUMBER(5) NOT NULL,
NM_ITEM VARCHAR2(40) NOT NULL,
DS_ITEM VARCHAR2(100) NOT NULL,
VL_PRECO_UNITARIO NUMBER(10,2) NOT NULL
);

 ALTER TABLE T_CPT_ITEM 
ADD CONSTRAINT PK_CPT_ITEM
 PRIMARY KEY (ID_ITEM);
 
 ALTER TABLE T_CPT_ITEM 
ADD CONSTRAINT FK_CPT_ITEM_CARDAPIO
 FOREIGN KEY (ID_CARDAPIO)
 REFERENCES T_CPT_CARDAPIO (ID_CARDAPIO);
 
 ALTER TABLE T_CPT_ITEM
ADD CONSTRAINT UN_CPT_ITEM_NOME
 UNIQUE (NM_ITEM);


/*----------- DDL da tabela T_CPT_ITEM_PEDIDO -----------*/

CREATE TABLE T_CPT_ITEM_PEDIDO (
QT_VENDIDA NUMBER(2) NOT NULL,
VL_PRECO_UNITARIO NUMBER(10,2) NOT NULL,
VL_TOTAL_ITEM NUMBER(10,2) NOT NULL
);

 ALTER TABLE T_CPT_ITEM_PEDIDO
ADD CONSTRAINT PK_CPT_ITEM_PEDIDO
 PRIMARY KEY (ID_ITEM, ID_PEDIDO);
 ALTER TABLE T_CPT_ITEM_PEDIDO
ADD CONSTRAINT FK_CPT_ITEM_PEDIDO_ITEM
 FOREIGN KEY (ID_ITEM)
 REFERENCES T_CPT_ITEM (ID_ITEM);
 ALTER TABLE T_CPT_ITEM_PEDIDO
ADD CONSTRAINT FK_CPT_ITEM_PEDIDO_PEDIDO
 FOREIGN KEY (ID_PEDIDO)
 REFERENCES T_CPT_PEDIDO (ID_PEDIDO);



